import { createRoot } from 'react-dom/client'
import { useEffect, useMemo, useState, type ReactNode } from 'react'
import './styles.css'

const STARTING_BALANCE = 10000
type Mode = 'home' | 'low' | 'market' | 'duel' | 'history' | 'rank' | 'wallet' | 'profile'
type Entry = { id: string; game: string; stake: number; delta: number; label: string; at: number }
function uid() { return crypto.randomUUID?.() || crypto.getRandomValues(new Uint32Array(2)).join('') }

function App() {
  const initial = useMemo(() => ({ balance: 0, history: [] as Entry[], username: 'Player' }), [])
  const [mode, setMode] = useState<Mode>('home')
  const [balance, setBalance] = useState(initial.balance)
  const [history, setHistory] = useState<Entry[]>(initial.history)
  const [username, setUsername] = useState(initial.username || 'Player')
  const [stake, setStake] = useState(500)
  const [risk, setRisk] = useState<'LOW' | 'BALANCED' | 'HIGH'>('LOW')
  const [result, setResult] = useState<string | null>(null)
  const [marketSide, setMarketSide] = useState<'UP' | 'DOWN' | null>(null)
  const [price, setPrice] = useState(100)
  const [time, setTime] = useState(15)
  const [duelCode, setDuelCode] = useState('')
  const [joinCode, setJoinCode] = useState('')
  const [syncing, setSyncing] = useState(true)

  useEffect(() => { (async () => { try { const response = await fetch('/api/bootstrap', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ username }) }); if (response.ok) { const data = await response.json(); setUsername(data.username); setBalance(data.balance) } } catch { /* API can be unavailable in static preview */ } finally { setSyncing(false) } })() }, [username])
  useEffect(() => { if (!marketSide || time <= 0) return; const timer = setInterval(() => { setTime(t => Math.max(0, t - 1)); setPrice(p => Math.max(70, Math.min(130, p + (Math.random() - .47) * 2.4))) }, 1000); return () => clearInterval(timer) }, [marketSide, time])
  useEffect(() => { if (time === 0 && marketSide) { const won = marketSide === (price >= 100 ? 'UP' : 'DOWN'); settle('MARKET', stake, won ? stake : -stake, won ? `MARKET WIN +${stake} SPIN` : `MARKET LOSS -${stake} SPIN`); setMarketSide(null) } }, [time, marketSide, price, stake])

  function settle(game: string, amount: number, delta: number, label: string) { if (amount > balance) return; setBalance(b => b + delta); setHistory(h => [{ id: uid(), game, stake: amount, delta, label, at: Date.now() }, ...h].slice(0, 100)); setResult(label) }
  async function playLow() { if (stake < 100 || stake > balance) return setResult('Choose a valid stake'); setResult('SETTLING…'); try { const response = await fetch('/api/low-risk', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ stake, risk, idempotencyKey: `${Date.now()}_${crypto.getRandomValues(new Uint32Array(1))[0]}` }) }); const data = await response.json(); if (!response.ok) return setResult(data.error || 'Round failed'); const delta = Number(data.profit); setBalance(Number(data.balance)); setHistory(h => [{ id: data.roundId, game: 'LOW RISK', stake, delta, label: data.result === 'WIN' ? `WIN +${delta} SPIN` : `LOSS ${delta} SPIN`, at: Date.now() }, ...h].slice(0, 100)); setResult(data.result === 'WIN' ? `WIN +${delta} SPIN` : `LOSS ${delta} SPIN`) } catch { setResult('Database unavailable — try again') } }
  function enterMarket(side: 'UP' | 'DOWN') { if (stake > balance || stake < 100) return; setBalance(b => b - stake); setMarketSide(side); setResult(null); setTime(15); setPrice(100) }
  function resetDemo() { setBalance(STARTING_BALANCE); setHistory([]); setResult(null) }

  return <div className="app"><header><button className="brand" onClick={() => setMode('home')}>SPIN<span>•</span></button><div className="header-actions"><button className="icon-button" aria-label="Notifications">◌</button><button className="avatar" onClick={() => setMode('profile')}>{username.slice(0, 1).toUpperCase()}</button></div></header><main>
    {mode === 'home' && <><section className="hero"><p className="eyebrow">PLAY THE ODDS</p><h1>Pick your<br /><em>side.</em></h1><p className="muted">A fast social prediction game. Practice with free SPIN credits.</p></section><BalanceCard balance={balance} onClick={() => setMode('wallet')} /><div className="section-label"><span>CHOOSE YOUR ARENA</span><span className="live-dot">● LIVE</span></div><div className="games"><GameCard icon="◉" title="Low Risk" desc="Limited downside. Up to +90%." tag="+90% / -10%" onClick={() => setMode('low')} /><GameCard icon="↗" title="Market" desc="Predict whether the fictional market moves up or down." tag="UP / DOWN" onClick={() => setMode('market')} /><GameCard icon="⚔" title="Duel" desc="Create or join a friend challenge." tag="PVP" onClick={() => setMode('duel')} /></div><div className="notice"><span className="gift">✦</span><div><b>{STARTING_BALANCE.toLocaleString()} SPIN</b><br /><small>Starter credits — no deposit required.</small></div></div><QuickStats history={history} balance={balance} /><BottomNav mode={mode} setMode={setMode} /></>}
    {mode === 'low' && <GameShell title="Low Risk" subtitle="Your downside is limited to 10%." back={() => setMode('home')}><RiskSelector risk={risk} setRisk={setRisk} /><StakeInput stake={stake} setStake={setStake} balance={balance} /><div className="payout-grid"><div><small>MAX LOSS</small><b>-{Math.round(stake * (risk === 'LOW' ? .1 : .5)).toLocaleString()}</b></div><div><small>POTENTIAL GAIN</small><b>+{Math.round(stake * (risk === 'HIGH' ? .7 : risk === 'BALANCED' ? .5 : .9)).toLocaleString()}</b></div><div><small>RETURN</small><b>{(stake + Math.round(stake * (risk === 'HIGH' ? .7 : risk === 'BALANCED' ? .5 : .9))).toLocaleString()}</b></div></div><button className="primary" disabled={syncing || stake > balance || balance < 100} onClick={playLow}>SPIN NOW <span>→</span></button>{result && <Result text={result} />}</GameShell>}
    {mode === 'market' && <GameShell title="Market Arena" subtitle="A fictional index game — not a financial instrument." back={() => setMode('home')}><div className="market"><div className="market-head"><span>SPIN INDEX <small>FICTIONAL</small></span><b>{price.toFixed(2)}</b></div><div className="chart"><i /><i /><i /><i /><div className="chart-line" /></div><div className="sentiment"><span>UP <b>64%</b></span><span>DOWN <b>36%</b></span></div><div className="market-meta"><span>{marketSide ? `POSITION: ${marketSide}` : 'CHOOSE A DIRECTION'}</span><b>{marketSide ? `${time}s` : '15s ROUND'}</b></div></div><StakeInput stake={stake} setStake={setStake} balance={balance} /><div className="direction"><button className={marketSide === 'UP' ? 'selected up' : 'up'} disabled={!!marketSide || stake > balance} onClick={() => enterMarket('UP')}>↗ UP</button><button className={marketSide === 'DOWN' ? 'selected down' : 'down'} disabled={!!marketSide || stake > balance} onClick={() => enterMarket('DOWN')}>↘ DOWN</button></div>{result && <Result text={result} />}</GameShell>}
    {mode === 'duel' && <GameShell title="Duel" subtitle="Challenge a friend with a five-character room code." back={() => setMode('home')}><div className="duel-box"><h2>Create a duel</h2><StakeInput stake={stake} setStake={setStake} balance={balance} /><button className="primary" onClick={() => setDuelCode(Math.random().toString(36).slice(2, 7).toUpperCase())}>CREATE DUEL</button>{duelCode && <div className="code">{duelCode}<small>Share this code with your friend</small></div>}<div className="rule" /><h2>Join a duel</h2><input className="text-input" placeholder="Enter code" value={joinCode} onChange={e => setJoinCode(e.target.value.toUpperCase().slice(0, 5))} /><button className="primary" disabled={joinCode.length !== 5} onClick={() => setResult(`JOINED DUEL ${joinCode}`)}>JOIN DUEL</button>{result && <Result text={result} />}</div></GameShell>}
    {(mode === 'history' || mode === 'wallet') && <GameShell title={mode === 'wallet' ? 'Wallet' : 'History'} subtitle={mode === 'wallet' ? 'Your demo SPIN balance and ledger.' : 'Your latest SPIN activity.'} back={() => setMode('home')}>{mode === 'wallet' && <BalanceCard balance={balance} onClick={() => undefined} />}{mode === 'wallet' && <div className="payout-grid wallet-stats"><div><small>TOTAL WON</small><b className="positive">+{history.filter(x => x.delta > 0).reduce((a, x) => a + x.delta, 0).toLocaleString()}</b></div><div><small>TOTAL LOST</small><b className="negative">{history.filter(x => x.delta < 0).reduce((a, x) => a + x.delta, 0).toLocaleString()}</b></div><div><small>GAMES</small><b>{history.length}</b></div></div>}<div className="list">{history.length ? history.map(x => <div className="row" key={x.id}><div><b>{x.game}</b><small>{x.label} · {new Date(x.at).toLocaleTimeString()}</small></div><strong className={x.delta >= 0 ? 'positive' : 'negative'}>{x.delta >= 0 ? '+' : ''}{x.delta.toLocaleString()}</strong></div>) : <div className="empty">No games yet. Play your first round.</div>}</div>{mode === 'history' && <button className="secondary" onClick={resetDemo}>RESET LOCAL DEMO</button>}<BottomNav mode={mode} setMode={setMode} /></GameShell>}
    {mode === 'rank' && <GameShell title="Leaderboard" subtitle="Weekly demo rankings. Compete, learn, improve." back={() => setMode('home')}><div className="list ranking"><div className="row"><div><b>1. {username}</b><small>You · {history.filter(x => x.delta > 0).length} wins</small></div><strong>{balance.toLocaleString()}</strong></div>{['Nova', 'Ace', 'Maya', 'KJ'].map((n, i) => <div className="row" key={n}><div><b>{i + 2}. {n}</b><small>Demo player</small></div><strong>{(9200 - i * 650).toLocaleString()}</strong></div>)}</div><BottomNav mode={mode} setMode={setMode} /></GameShell>}
    {mode === 'profile' && <GameShell title="Profile" subtitle="Your SPIN player profile." back={() => setMode('home')}><div className="profile-card"><div className="profile-avatar">{username.slice(0, 1).toUpperCase()}</div><h2>{username}</h2><p className="muted">Demo player</p><div className="rule" /><p><small>ACCOUNT STATUS</small><br /><b>Active · Demo mode</b></p><button className="secondary" onClick={() => { const next = prompt('Choose a display name', username); if (next) setUsername(next.slice(0, 24)) }}>EDIT DISPLAY NAME</button></div><BottomNav mode={mode} setMode={setMode} /></GameShell>}
  </main><footer><span>SPIN V1 · PLAY MONEY</span><span>Neon connected</span></footer></div>
}

function BalanceCard({ balance, onClick }: { balance: number; onClick: () => void }) { return <button className="balance-card" onClick={onClick}><div><small>AVAILABLE BALANCE</small><strong>{balance.toLocaleString()} <i>SPIN</i></strong></div><span>→</span></button> }
function QuickStats({ history, balance }: { history: Entry[]; balance: number }) { return <div className="quick-stats"><div><small>GAMES PLAYED</small><b>{history.length}</b></div><div><small>WIN RATE</small><b>{history.length ? Math.round(history.filter(x => x.delta > 0).length / history.length * 100) : 0}%</b></div><div><small>RANK</small><b>#1</b></div></div> }
function BottomNav({ mode, setMode }: { mode: Mode; setMode: (m: Mode) => void }) { return <nav className="bottom-nav"><button className={mode === 'home' ? 'active' : ''} onClick={() => setMode('home')}>⌂<small>HOME</small></button><button className={['low', 'market', 'duel'].includes(mode) ? 'active' : ''} onClick={() => setMode('low')}>＋<small>PLAY</small></button><button className={mode === 'rank' ? 'active' : ''} onClick={() => setMode('rank')}>♛<small>RANK</small></button><button className={mode === 'wallet' ? 'active' : ''} onClick={() => setMode('wallet')}>▣<small>WALLET</small></button></nav> }
function GameCard({ icon, title, desc, tag, onClick }: { icon: string; title: string; desc: string; tag: string; onClick: () => void }) { return <button className="game-card" onClick={onClick}><div className="icon">{icon}</div><div className="card-copy"><h2>{title}</h2><p>{desc}</p></div><span className="tag">{tag}</span><span className="arrow">→</span></button> }
function GameShell({ title, subtitle, children, back }: { title: string; subtitle: string; children: ReactNode; back: () => void }) { return <section className="game-shell"><button className="back" onClick={back}>← HOME</button><p className="eyebrow">SPIN ARENA</p><h1>{title}</h1><p className="muted">{subtitle}</p>{children}</section> }
function StakeInput({ stake, setStake, balance }: { stake: number; setStake: (n: number) => void; balance: number }) { const max = Math.max(100, balance); const value = Math.min(stake, max); return <div className="stake"><div className="stake-top"><small>STAKE</small><strong>{value.toLocaleString()} SPIN</strong></div><input aria-label="Stake amount" type="range" min="100" max={max} step="100" value={value} onChange={e => setStake(Number(e.target.value))} /><div className="quick"><button onClick={() => setStake(Math.min(100, balance))}>100</button><button onClick={() => setStake(Math.min(500, balance))}>500</button><button onClick={() => setStake(Math.min(1000, balance))}>1K</button><button onClick={() => setStake(Math.min(balance, 5000))}>MAX</button></div></div> }
function RiskSelector({ risk, setRisk }: { risk: string; setRisk: (risk: 'LOW' | 'BALANCED' | 'HIGH') => void }) { return <div className="risk-selector">{[['LOW', '10% down', '90% up'], ['BALANCED', '50% down', '50% up'], ['HIGH', '70% down', '70% up']].map(([key, down, up]) => <button className={risk === key ? 'active' : ''} key={key} onClick={() => setRisk(key as 'LOW' | 'BALANCED' | 'HIGH')}><b>{key}</b><small>{down} · {up}</small></button>)}</div> }
function Result({ text }: { text: string }) { return <div className={`result ${text.includes('WIN') || text.includes('JOINED') ? 'win' : 'loss'}`}>{text}</div> }
createRoot(document.getElementById('root')!).render(<App />)
