import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const STARTING_BALANCE=10000;
type Mode='home'|'low'|'market'|'duel'|'history'|'leaderboard';
type Entry={id:string;game:string;stake:number;delta:number;label:string;at:number};
type Persisted={balance:number;history:Entry[];username:string;userId?:string};
const KEY='spin:v2';
function load():Persisted{try{const x=JSON.parse(localStorage.getItem(KEY)||'');return x?.balance>=0?x:{balance:STARTING_BALANCE,history:[],username:'Player'};}catch{return{balance:STARTING_BALANCE,history:[],username:'Player'}}}
function uid(){return crypto.randomUUID?.()||Math.random().toString(36).slice(2)}

function App(){
 const initial=React.useMemo(load,[]);const[mode,setMode]=React.useState<Mode>('home');const[balance,setBalance]=React.useState(initial.balance);const[history,setHistory]=React.useState<Entry[]>(initial.history);const[username,setUsername]=React.useState(initial.username||'Player');const[userId,setUserId]=React.useState(initial.userId||'');const[stake,setStake]=React.useState(500);const[result,setResult]=React.useState<string|null>(null);const[price,setPrice]=React.useState(100);const[startPrice,setStartPrice]=React.useState(100);const[marketSide,setMarketSide]=useState<'UP'|'DOWN'|null>(null);const[time,setTime]=React.useState(15);const[duelCode,setDuelCode]=React.useState('');const[joinCode,setJoinCode]=React.useState('');const[syncing,setSyncing]=React.useState(true);
 React.useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({balance,history,username,userId}));},[balance,history,username,userId]);
 React.useEffect(()=>{(async()=>{try{const r=await fetch('/api/bootstrap',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username})});if(r.ok){const x=await r.json();setUserId(x.userId);setUsername(x.username);setBalance(x.balance)}}catch{}finally{setSyncing(false)}})()},[]);
 React.useEffect(()=>{if(mode!=='market'||!marketSide||time<=0)return;const id=setInterval(()=>{setTime(t=>Math.max(0,t-1));setPrice(p=>Math.max(70,Math.min(130,p+(Math.random()-.47)*2.4)));},1000);return()=>clearInterval(id)},[mode,marketSide,time]);
 React.useEffect(()=>{if(mode==='market'&&time===0&&marketSide){const won=marketSide===(price>=startPrice?'UP':'DOWN');settleLocal('MARKET',stake,won?stake:-stake,won?`MARKET WON +${stake} SPIN`:`MARKET LOST -${stake} SPIN`);setMarketSide(null)}},[time]);
 function settleLocal(game:string,s:number,delta:number,label:string){if(s>balance)return;setBalance(b=>b+delta);setHistory(h=>[{id:uid(),game,stake:s,delta,label,at:Date.now()},...h].slice(0,100));setResult(label)}
 async function playLow(){if(!userId||stake<=0)return;setResult('SETTLING…');try{const r=await fetch('/api/low-risk',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({userId,stake})});const x=await r.json();if(!r.ok){setResult(x.error||'Round failed');return}const delta=Number(x.profit);setBalance(Number(x.balance));setHistory(h=>[{id:x.roundId,game:'LOW RISK',stake,delta,label:x.result==='WIN'?`WIN +${delta} SPIN`:`LOSS ${delta} SPIN`,at:Date.now()},...h].slice(0,100));setResult(x.result==='WIN'?`WIN +${delta} SPIN`:`LOSS ${delta} SPIN`)}catch{setResult('Database unavailable — try again')}
 }
 function enterMarket(side:'UP'|'DOWN'){if(stake>balance)return;setBalance(b=>b-stake);setMarketSide(side);setResult(null);setTime(15);setPrice(100);setStartPrice(100)}
 function createDuel(){setDuelCode(Math.random().toString(36).slice(2,7).toUpperCase())}
 function resetDemo(){setBalance(STARTING_BALANCE);setHistory([]);setResult(null)}
 return <div className="app"><header><button className="brand" onClick={()=>setMode('home')}>SPIN<span>•</span></button><div className="balance"><small>{syncing?'SYNCING':'BALANCE'}</small><strong>{balance.toLocaleString()} SPIN</strong></div></header><main>
 {mode==='home'&&<><section className="hero"><p className="eyebrow">PLAY THE ODDS</p><h1>Pick your<br/><em>side.</em></h1><p className="muted">A fast social prediction game. Practice with free SPIN credits.</p></section><div className="games"><GameCard icon="🟢" title="Low Risk" desc="Limited downside. Up to +90%." tag="+90% / -10%" onClick={()=>setMode('low')}/><GameCard icon="📈" title="Market" desc="Predict whether the fictional market moves up or down." tag="UP / DOWN" onClick={()=>setMode('market')}/><GameCard icon="⚔️" title="Duel" desc="Create or join a friend challenge." tag="PVP" onClick={()=>setMode('duel')}/></div><div className="notice">🎁 <b>{STARTING_BALANCE.toLocaleString()} SPIN</b> starter credits — no deposit required.</div><nav className="nav"><button onClick={()=>setMode('history')}>History</button><button onClick={()=>setMode('leaderboard')}>Leaderboard</button><button onClick={()=>{const n=prompt('Choose a display name',username);if(n){setUsername(n.slice(0,24));setResult('Name saved')}}}>Profile</button></nav></>}
 {mode==='low'&&<GameShell title="Low Risk" subtitle="Your downside is limited to 10%." back={()=>setMode('home')}><div className="risk-display"><div className="risk-circle">90<small>%</small><span>MAX UPSIDE</span></div><div><div className="stat"><b>+90%</b><span>WIN</span></div><div className="stat"><b>-10%</b><span>LOSS</span></div></div></div><StakeInput stake={stake} setStake={setStake} balance={balance}/><button className="primary" disabled={!userId||syncing} onClick={playLow}>SPIN NOW <span>→</span></button>{result&&<Result text={result}/>}</GameShell>}
 {mode==='market'&&<GameShell title="Market Arena" subtitle="Predict the direction of a fictional market." back={()=>setMode('home')}><div className="market"><div className="market-head"><span>SPIN INDEX</span><b>{price.toFixed(2)}</b></div><div className="chart"><div className="line" style={{height:`${Math.min(92,Math.max(20,price-65))}%`}}/></div><div className="market-meta"><span>{marketSide?`POSITION: ${marketSide}`:'CHOOSE A DIRECTION'}</span><b>{marketSide?`${time}s`:'15s ROUND'}</b></div></div><StakeInput stake={stake} setStake={setStake} balance={balance}/><div className="direction"><button className={marketSide==='UP'?'selected up':'up'} disabled={!!marketSide} onClick={()=>enterMarket('UP')}>📈 UP</button><button className={marketSide==='DOWN'?'selected down':'down'} disabled={!!marketSide} onClick={()=>enterMarket('DOWN')}>📉 DOWN</button></div>{result&&<Result text={result}/>}</GameShell>}
 {mode==='duel'&&<GameShell title="Duel" subtitle="Challenge a friend with a five-character room code." back={()=>setMode('home')}><div className="duel-box"><h2>Create a duel</h2><StakeInput stake={stake} setStake={setStake} balance={balance}/><button className="primary" onClick={createDuel}>CREATE DUEL</button>{duelCode&&<div className="code">{duelCode}<small>Share this code with your friend</small></div>}<hr/><h2>Join a duel</h2><input className="text-input" placeholder="Enter code" value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())}/><button className="primary" onClick={()=>joinCode.length===5&&setResult(`JOINED DUEL ${joinCode}`)}>JOIN DUEL</button>{result&&<Result text={result}/>}</div></GameShell>}
 {mode==='history'&&<GameShell title="History" subtitle="Your latest SPIN activity." back={()=>setMode('home')}><div className="list">{history.length?history.map(x=><div className="row" key={x.id}><div><b>{x.game}</b><small>{new Date(x.at).toLocaleTimeString()}</small></div><strong className={x.delta>=0?'positive':'negative'}>{x.delta>=0?'+':''}{x.delta.toLocaleString()}</strong></div>):<div className="empty">No games yet. Play your first round.</div>}</div><button className="secondary" onClick={resetDemo}>RESET LOCAL DEMO</button></GameShell>}
 {mode==='leaderboard'&&<GameShell title="Leaderboard" subtitle="Demo rankings — online rankings come next." back={()=>setMode('home')}><div className="list"><div className="row"><div><b>1. {username}</b><small>You</small></div><strong>{balance.toLocaleString()}</strong></div>{['Nova','Ace','Maya','KJ'].map((n,i)=><div className="row" key={n}><div><b>{i+2}. {n}</b><small>Demo player</small></div><strong>{(9200-i*650).toLocaleString()}</strong></div>)}</div></GameShell>}
 </main><footer><span>SPIN V1 • PLAY MONEY</span><span>Neon connected</span></footer></div>
}
function GameCard({icon,title,desc,tag,onClick}:{icon:string,title:string,desc:string,tag:string,onClick:()=>void}){return <button className="game-card" onClick={onClick}><div className="icon">{icon}</div><div className="card-copy"><h2>{title}</h2><p>{desc}</p></div><span className="tag">{tag}</span><span className="arrow">→</span></button>}
function GameShell({title,subtitle,children,back}:{title:string,subtitle:string,children:React.ReactNode,back:()=>void}){return <section className="game-shell"><button className="back" onClick={back}>← HOME</button><p className="eyebrow">SPIN ARENA</p><h1>{title}</h1><p className="muted">{subtitle}</p>{children}</section>}
function StakeInput({stake,setStake,balance}:{stake:number,setStake:(n:number)=>void,balance:number}){const max=Math.max(100,balance);return <div className="stake"><div><small>STAKE</small><strong>{Math.min(stake,max).toLocaleString()} SPIN</strong></div><input type="range" min="100" max={max} step="100" value={Math.min(stake,max)} onChange={e=>setStake(Number(e.target.value))}/><div className="quick"><button onClick={()=>setStake(Math.min(100,balance))}>100</button><button onClick={()=>setStake(Math.min(500,balance))}>500</button><button onClick={()=>setStake(Math.min(1000,balance))}>1K</button><button onClick={()=>setStake(Math.min(balance,5000))}>MAX</button></div></div>}
function Result({text}:{text:string}){return <div className={`result ${text.includes('WON')||text.startsWith('WIN')||text.includes('JOINED')?'win':'loss'}`}>{text}</div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
